<?php

/**
 * @file
 * Module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\Entity\Node;

/**
 * Presave.
 */
function fizruk_entity_presave(EntityInterface $entity) {
  if (method_exists($entity, 'getType') && $entity->getType() == 'result') {
    $entity->title->setValue(date('d-M-Y'));
  }
}

/**
 * Form Alter.
 */
function fizruk_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'views_exposed_form') {
    $form["field_result_date_value"]['#type'] = 'date';
    $form["field_result_date_value_1"]['#type'] = 'date';
  }
}

/**
 * Views pre_render.
 */
function fizruk_views_pre_render($view) {
  $results = [];
  //dsm($view->result);
  foreach ($view->result as $key => $value) {
    $results[$value->nid] = [
      'nid' => $value->nid,
      'date' => $value->node__field_result_date_field_result_date_value,
    ];
  }
  //dsm($results);
  $itogo_distance = 0;
  foreach ($results as $nid => $value) {
    $node = Node::load($nid);
    $uid = $node->uid->entity->id();
    $distance = $node->field_result_distance->value;
    $itogo_distance = $itogo_distance + $distance;
  }
  drupal_set_message("итоговая дистанция: " . $itogo_distance);
}
